import { ChakraProvider } from '@chakra-ui/react';

export const metadata = {
  title: 'Next Auth tutorial',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <ChakraProvider>
        {children}
      </ChakraProvider>
      </body>
    </html>
    
  )
}
